### ISSUE TITLE
FactoryBotへの移行

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#100]
テストで使っているFactoryGirlがFactoryBotに改名され、以前の名前での使用は非推奨になったため、FactoryBotを使うようにする。

参照: https://github.com/thoughtbot/factory_bot/blob/4-9-0-stable/UPGRADE_FROM_FACTORY_GIRL.md

**Comment by koi-chan** [comment]
commit: e2d156bc01d027b95a848476180247ce5d4cba14 にて、上記ウェブページの通りの操作を実行した。

**Comment by koi-chan** [comment]
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:
date { Mon, 23 Jan 2017 }
To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:
rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct
. (called from block (2 levels) in <top (required)> at /home/travis/build/cre-ne-jp/log-archiver/test/factories/channel_browse/days.rb:4)

このような非推奨ワーニングが大量に出る。
https://qiita.com/jnchito/items/81637bbdf66c2662eacf
こう言うことらしい。

**Comment by koi-chan** [comment]
branch: upgrade-factorygirl-bot (commit: e2d156b)は、rails50-FactoryBot で同じ事を行なうために削除した。

**Comment by koi-chan** [comment]
静的属性を、動的属性に書き換えた。

**Comment by koi-chan** [comment]
#120 にて master に取り込みました。
