### ISSUE TITLE
トップページのインターフェースを決める

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#11]
どのような項目があったら使いやすいか考えながら決める。

**Comment by ochaochaocha3** [comment]
* 簡易指定
* 詳細指定

# 簡易指定

* チャンネルと日付。
* チャンネルは長くなるのでドロップダウンリストにする。
* 日付：
    * 今日
    * 昨日
    * 日付指定：テキストボックス＋カレンダー、「閲覧」ボタン

# 詳細指定

* フリーワード
* チャンネル（ドロップダウンリスト）
* 開始日時
* 終了日時

**Comment by ochaochaocha3** [comment]
キーワードをどうするか。

WordPressのようなタグ形式にするとか、キーワード自体の検索ができるようにするとか（キーワードが多そうなので）。

**Comment by koi-chan** [comment]
画面のイメージですが、雑なものですが描いてみました。
簡易指定の画面案は2つあります。どちらの方が良さそうだと思いますか？

![2016-12-06 14 24 41](https://cloud.githubusercontent.com/assets/8256803/20914075/371bdec4-bbc0-11e6-8315-0c67b26d382d.jpg)
![2016-12-06 14 24 46](https://cloud.githubusercontent.com/assets/8256803/20914074/371af252-bbc0-11e6-8428-a0dca5b797a5.jpg)

**Comment by ochaochaocha3** [comment]
簡易指定は2番のものが分かりやすそうです。

**Comment by ochaochaocha3** [comment]
だいたいできてきましたが、詳細画面（キーワード検索）でチャンネルを複数選択できるようにするのが少し難しそうです。

これはフォームのデザインというより、検索結果画面で複数チャンネルに含まれるメッセージをどのように表示するかの案が、今のところうまく浮かばないためです。特に一定件数でページ区切りを行うための条件が難しいです（例：「新しいものから10件」の場合、単純に新しいもの10件を取ろうとすると、日付やチャンネルが中途半端なところで切れてしまう）。

そこで、最初は詳細画面のチャンネル選択は単数で選択するようにして、後で可能ならば複数選択できるようにするようにしたいと考えました。単数にしておけば最低限の機能を早く提供できます。

**Comment by koi-chan** [comment]
キーワード周りは後回しでいいですよね、関連する未完了のものは他に何かありますか？

**Comment by ochaochaocha3** [comment]
画面については今のところは完了していると思います。

**Comment by koi-chan** [comment]
ではこの issue はとじておきます。
