### ISSUE TITLE
チャンネルごとに noindex 出来るようにする

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#111]
同じチャンネルを複数の LogArchiver で取得・公開すると、同じ内容のウェブサイトとして SEO の問題がある。
ログの取得・公開は行なうが、そのチャンネルのページに meta タグの noindex を指定できるようにしたい。
もしくは、link タグの canonical で任意のウェブページを指定できるようにしたい。

**Comment by koi-chan** [comment]
canonical を設定する方向で実装中。

マスターサイトを固定URLにする場合の実装は完了した。
個別ログ表示のページにおいて、ログの日付をURLに埋め込めるようにする。

**Comment by ochaochaocha3** [comment]
鯉さんが `<link rel="canonical">` を使う方法で実装しました！
