### ISSUE TITLE
rails50: rake db:migrate が失敗する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#116]
新規にデータベースを設定しようとマイグレーションを行なうと、次の位置でエラー終了する。

[db/migrate/20170617130524_recreate_conversation_messages_irc_user_id.rb:13](https://github.com/cre-ne-jp/log-archiver/blob/rails50/db/migrate/20170617130524_recreate_conversation_messages_irc_user_id.rb#L13)

Mysql2::Error: Cannot drop column 'irc_user_id': needed in a foreign key constraint 'fk_rails_de9941562b': ALTER TABLE `conversation_messages` DROP `irc_user_id`

**Comment by ochaochaocha3** [comment]
これは難しそうです。 04e3f76 で、`irc_user_id` に対応するものがないとき（Tiarraログファイルのインポート等で発生する）、ダミーの番号として `0` が入るようにこのマイグレーションを入れていました。このときも似たようなエラーが頻発したように思います。

RailsのコンソールかSQLの直接実行で、

* `irc_user_id` が `NULL` になっているものを一旦 `0` に設定する（`irc_user_id` が `0` のものはダミーユーザーにしておく）
* 外部キー制約を消しておく

といったことが必要だったかもしれません（自分で解消したときも、応急処置で「良くないやり方だな」と感じていました）。

**Comment by ochaochaocha3** [comment]
単に新規データベースを作る場合、`db:migrate` より `db:setup` で schema.rb の情報を直接使って作る方がSQLの実行量も少なくて速く、トラブルなくできるはずですが、Railsのバージョンアップ中なので問題が発生しないかやってみないと分からないですね。

**Comment by koi-chan** [comment]
rails4.2 の master ブランチはデータベースのエラーなく実行することができます。
rails5.0.0 に移行中の rails50 ブランチでは、エラー終了してしまいます。

ブランチを切り替えた時点では、マイグレーションファイル群に書き換えはなかったのですが、エラーが出るようになりました。マイグレーションファイルの互換性を維持するため、すべてに 4.2 互換のオプションを付加しても、やはりエラーが出てしまいます。
rails4.2 では、rake db:migrate がうまく動くということ自体、どうしてなのか分からない状態です。
単純に rails5.0.0 のバグだったらいいのですが、そうでなかった場合は db/schema.rb を再作成する必要が出てきた時のためにも、何らかの修正をしたいです。

**Comment by koi-chan** [comment]
インデックスサイズなどの設定が反映されていないのかもしれません。要検証

**Comment by koi-chan** [comment]
PR #121 にて、マイグレーションは通るようになったのでこの issue は閉めます。
