### ISSUE TITLE
db:migrateの後、db/schema.rbが変更されてデータベース更新時にエラーが発生する

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#124]
`rails db:migrate` の後、db/schema.rb が変更される。変更後、データベース更新時にエラーが発生するためテストが通らなくなる。

Rails 4.2ではこの問題は発生せず、Rails 5から発生するようである。

* 関連記事？: https://stackoverflow.com/questions/39769981/why-did-rails-5-changed-index-to-foreign-key

# db:migrate 前後の db/schema.rb の差分

```diff
diff --git a/db/schema.rb b/db/schema.rb
index 19db4de..2631b6f 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -10,7 +10,7 @@
 #
 # It's strongly recommended that you check this file into your version control system.

-ActiveRecord::Schema.define(version: 20170704121029) do
+ActiveRecord::Schema.define(version: 20170617130524) do

   create_table "channel_last_speeches", force: :cascade, options: "ENGINE=Mroonga DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC" do |t|
     t.integer  "channel_id"
@@ -108,5 +108,7 @@ ActiveRecord::Schema.define(version: 20170704121029) do
     t.index ["username"], name: "index_users_on_username", unique: true, using: :btree
   end

+  add_foreign_key "channel_last_speeches", "channels", name: "channel_id"
   add_foreign_key "channel_last_speeches", "conversation_messages", name: "conversation_message_id"
+  add_foreign_key "conversation_messages", "channels", name: "channel_id"
```

**Comment by koi-chan** [comment]
Rails 5.2 では、マイグレーション失敗後に、データベースを削除することも出来なくなります。

マイグレーションに失敗したときのエラーメッセージは以下の通りです。
```
[irc_user_id のインデックスの再構築]
-- add_index(:conversation_messages, :irc_user_id)
   -> 0.0073s
== 20170617130524 RecreateConversationMessagesIrcUserId: migrated (0.4949s) ===

rails aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'log_archiver_dev.#sql2-530-248' doesn't exist: SELECT fk.referenced_table_name AS 'to_table',
       fk.referenced_column_name AS 'primary_key',
       fk.column_name AS 'column',
       fk.constraint_name AS 'name',
       rc.update_rule AS 'on_update',
       rc.delete_rule AS 'on_delete'
FROM information_schema.referential_constraints rc
JOIN information_schema.key_column_usage fk
USING (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = database()
  AND fk.table_name = 'channel_last_speeches'
  AND rc.constraint_schema = database()
  AND rc.table_name = 'channel_last_speeches'
```

**Comment by ochaochaocha3** [comment]
rails52-fix-migration ブランチにおいて、20161128183000版で `conversation_messages` テーブルに外部キー制約をつけないようにした結果、20170617130524版でのエラーが起こらなくなりました: 0a86836
このブランチでの `db:create` → `db:migrate` が実行できるかどうかの確認を行っていただければ幸いです。

ただ、過去のマイグレーションを変更することになるため、既存のデータベースと整合するかが気になります。現在は `irc_user` の行を消し、そのユーザーの発したメッセージを同時に消す処理は含めていないので大丈夫だとは思いますが。

新しいマイグレーションを作って外部キー制約を外すこと（`drop_foreign_key`）も試したのですが、Mroongaが対応していないため一度 `drop_table` しようとし、別のテーブルの外部キー制約に引っかかって `drop_table` が成功せず全体として失敗するということになるようでした。

**Comment by ochaochaocha3** [comment]
マイグレーションの20170617130524版が必要になった原因は、実はテーブルの設計ミスです。

IRCボットで拾ったメッセージにはホスト名が入っているので `irc_users` との対応が必ずありますが、Tiarraのログには必要な情報が含まれず、`irc_user_id` が `NULL` になってしまうという問題があります。これに加えて、[Mroongaの制限](http://mroonga.org/ja/docs/reference/limitations.html#limitations-about-the-value-of-columns)により `NULL` が `0` になってしまいます。`irc_users` の `id` には `AUTO_INCREMENT` が設定されており、原則として1以上にしかならないため、存在しないIRCユーザーが指定されていることになり、これはデータの不整合です。

したがって、本当は `conversation_messages` に `irc_user_id` を含めてはならず、発言とIRCユーザーを紐付けるテーブルが必要になります。特定の（ホスト名まで分かっている）IRCユーザーの発言を取り出すときには、テーブルの内部結合（`INNER JOIN`）を使います。

本来はこのようにテーブルを設計し直すべきなのですが、上記のように、外部キー制約を1つ落とそうとしただけで失敗するような状態なので、かなり慎重に行う必要がありそうです。

**Comment by ochaochaocha3** [comment]
#151 のマージにより、やっと解決しました！
