### ISSUE TITLE
NickServ にログインする

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#14]
IRCボットに、NickServ にログインするプラグインを実装する

**Comment by koi-chan** [comment]
2432199 -> 設定ファイル中でデフォルト設定という概念をなくしました。
設定を階層化してしまうとうまくデフォルト設定で上書きされないようだからです。
それとも全ての設定を同じ階層に置くほうが良いでしょうか？

33cae0d -> ログインできたか確認する機能を実装すると ToDo に書いた物の、IRCのようにクライアント・サーバ間の通信が非同期なプロトコルで、どうやって「ログインをした後」に「ログインできたことを確認する」か、悩んでいます。
この機能は無くてもいいですかね？

**Comment by koi-chan** [comment]
ログインの後に、認証に通ったか確認するにはどうすればいいか。

**Comment by koi-chan** [comment]
XMLRPCで最終ログイン時間を調べたり、ログインしているか調べたりする方向でいってみたいと思います。

**Comment by ochaochaocha3** [comment]
分かりました。

ちょっと古いかもしれませんが、昔のるびまにXMLRPCの紹介記事があったので、貼っておきます。
[Rubyist Magazine - 標準添付ライブラリ紹介 【第 1 回】 XMLRPC4R](http://magazine.rubyist.net/?0007-BundledLibraries)

**Comment by koi-chan** [comment]
ちょうどそのページをみていました。
ありがとうございます。

**Comment by koi-chan** [comment]
#14 にて実装完了。
