### ISSUE TITLE
ログインした後の選択ページに、バージョンを表示する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#146]
ログインした後の、見出しに「管理」があるページ (/admin) に、稼働中のバージョンを表示させる。

**Comment by koi-chan** [comment]
commit: 19b2924c2c39668b3069979469d8e776126b87a0 にて実装してみました。

config/version.rb がこの回送になければ行けない理由は何だったでしょうか。
そして、その中身でコミットIDを定数ではなく変数に受けていたのは何故だったでしょうか。

http://gyazo.cre.jp/data/de60656401c0f5f1f4b9997785f1327a.png

**Comment by ochaochaocha3** [comment]
config/version.rb の初回コミットは c57cc9d4e8c32463da2b3f5345140c4ffd5c4f19 で、このときから今の場所にあったようです。

変数で受け取っていた理由は、ファイルの読み込み順を考慮して、あるいはキャッシュするようにしたのが後からだったので、そのときあった関数をそのままにしていただけかもしれません。[RGRBのVersionプラグインでは定数で実装されていた](https://github.com/cre-ne-jp/rgrb/blob/b199ccf7bfbe01efc8cb3b3053cf353e400360e1/lib/rgrb/version.rb)ので、それで大丈夫なら定数に合わせた方が良いでしょうか。

**Comment by koi-chan** [comment]
初回コミットからここにあったのなら、RGRB とファイル配置を揃えていたのかもしれません。rails の初期化に必要なファイルになるので、移動したいと思います。
もしくは、元の場所で定数でのバージョン定義だけ残し、config/initializers/version.rb にて変数・メソッドなどの方法でバージョン情報とコミットIDを取得できるようにするのでも良いかもしれません。
