### ISSUE TITLE
Ruby 2.4 への対応

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#15]
Ruby 2.4.0 で実行できるようにする。
ruby24 ブランチで、Travis-CIでのチェックは開始した。 -> b791eccc50641a05bd4a0b867adacc83cc20ed3b

json 1.8.3 を使い続けているのが原因で、どうやら(このバージョンが？) ruby2.4.0 でビルドできないのが原因である。
ただ、ほかの gem と依存関係にあるためと思われるのだが、bundle update の対象にならない。

rails ごとアップデートしてしまったものだろうか(現在は v4.2.6)。

**Comment by ochaochaocha3** [comment]
Railsごと更新する方針で適用していきたいと思います。
