### ISSUE TITLE
リリースされた rails6.0 にアップデートする

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#154]
rails 6.0 が8月16日にリリースされたようです。
依存パッケージを更新し、rails6.0 で動作するようにします。

**Comment by koi-chan** [comment]
rails60 ブランチにて更新中です。

commit-id: 4fa53fd までで、ruby-gems 'rails' と依存ライブラリの更新を完了し、アップデートタスクを実行しました。
テストを実行すると全てパスするものの、`DEPRECATION WARNING` が大量に出ているので、今後はこれを修正します。

**Comment by ochaochaocha3** [comment]
ありがとうございます！
