### ISSUE TITLE
json:util:complement_user_host: 全チャンネルにおいて正しく状態を変化させる

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#163]
PR #159 で途中まで作られたユーザー名、ホスト補完処理を完成させる。

**Comment by ochaochaocha3** [comment]
https://github.com/cre-ne-jp/log-archiver/pull/159#issuecomment-531081737

> json:util:complement_user_host による NICK, PART, QUIT メッセージの補完時に、連続する1つ目のメッセージしか補完できないバグがありました。
> 複数のチャンネルに入っているとき、これらのメッセージは入っているチャンネルの数だけ繰り返されます。しかし現在の実装では、最初のメッセージを処理する際にキャッシュされた user, host を破棄してしまいます。そのため、チャンネルの項目だけが異なる同じメッセージが2つ以上続く場合、2つ目以降はキャッシュデータがないため保管が行なわれません。
> NICK, QUIT に関しては、これらのメッセージ専用の、補完する user, host を保存する別のキャッシュを用意することで対応できると考えています。ただし、元のIRCメッセージが同じだったかどうかを判断する根拠はタイムスタンプとニックネーム以外では判断できません。
>
> また同じく complement_user_host タスクに、PART メッセージの処理時には上記のバグに加え、にたようで本質的には異なる、以下のバグがありました。
> 複数のチャンネルに入っていた後に、1つ以上のチャンネルには入ったままいずれかのチャンネルから退出したとき、入ったままになっているチャンネルがあるのにもかかわらずキャッシュが削除され、移行のメッセージの user, host が補完されなくなるというものです。

**Comment by ochaochaocha3** [comment]
https://github.com/cre-ne-jp/log-archiver/pull/159#issuecomment-531633288

> 全体としては、チャンネルごとに参加者のユーザー名、ホスト、ニックネームを記録しておかなければならないように感じました。

**Comment by koi-chan** [comment]
チャンネル名・ニックネームをキーとするキャッシュを用いるように変更しました。
これにより上記2つのバグ発生の前提となる、複数のチャンネルのメッセージが保存された JSON ファイルを処理できるようになりました。

正しいデータが与えられている場合は動きますが、一部が欠損したデータを与えられた場合はチャンネルによって補完が効かない可能性があります。
例えば、同一のIRCネットワークで取得された違うチャンネルであっても、IRCプロトコル的にはニックネームさえ同じであれば user, host は同じ事が保証されます。
しかし現在の実装ではキャッシュデータの管理上、JOIN メッセージが一部のチャンネルで欠損しているとき、チャンネル名とニックネームの両方が同一でなければ、同一クライアントであると認識できず補完が行なわれません。
