### ISSUE TITLE
メッセージのフラグメント識別子を内容から作る

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#169]
# 背景・目的

現在、同じ内容のメッセージについてもデータベースに挿入した順番によってパーマリンクが変わってしまう（つまり、パーマリンクが意味を成さない）という問題がある。これは、日ごとのメッセージ一覧画面におけるフラグメント識別子（URLの `#` 以降の部分）をメッセージのIDから作っている（`"c#{id}"` または `"m#{id}"` とする）ため。この方法は簡単だが、メッセージの内容と関係なくIDによって結果が変わってしまう。

そこで、上記の問題を解消することを目的として、メッセージの内容と対応するIDを作る処理を実装することを目指す。

# 方法

以下の要素を含む空白区切り文字列を作り、それにハッシュ関数を適用することで、メッセージの内容と対応するIDを作る。

* タイムスタンプ：UNIX時間
* メッセージの種類：Join、Privmsgなど
* ニックネーム
* メッセージ本体：Joinならチャンネル、Privmsgなら発言内容、など

ハッシュ関数としては、[16進数8文字（32ビット = 4バイト）を返すもの][KEINOS]がちょうど良さそう。8文字ならば手入力が可能であるし、日ごとにページが分かれているので、衝突の確率も十分に低いと考えられる。用途から、[fnv1a][fnv]32が候補。このアルゴリズムを高速に実行するgemである[cfnv][cfnv]もある。

表示ごとにハッシュ値を作っていては遅くなる可能性があるため、もしかするとデータベースのテーブルにハッシュ値の列を作るのが良いかもしれない。速度に問題がなければ、表示ごとに作る。

# 参考文献

* KEINOS: [hashアルゴリズムとハッシュ値の長さ一覧][KEINOS], Qiita
* Wikipedia: [Fowler–Noll–Vo hash function][fnv]
* g-ken: [g-ken/cfnv][cfnv], GitHub

[KEINOS]:https://qiita.com/KEINOS/items/c92268386d265042ea16
[fnv]:https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function
[cfnv]:https://github.com/g-ken/cfnv

**Comment by koi-chan** [comment]
キーワード機能 (issue #13 )・メッセージ非表示機能 (issue #6 ) の実装などにも、内容で決まるデータベース構造とは独立した何らかの識別子があると便利だと思います。

そして作るのであれば、識別子でメッセージを検索できるよう、データベースにあらかじめ保存しておいたほうが応用が利くのではないでしょうか。

**Comment by ochaochaocha3** [comment]
識別子で検索する機能があれば、確かにチャンネルや日付をたどってメッセージを探しにいく手間がなくなるので、便利ですね。データベースに保存することができたので、将来的にその検索画面も作りたいです。
