### ISSUE TITLE
DEPRECATED になっている古い CodeClimate 設定を改善する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#176]
ruby-gems "codeclimate-test-reporter" を使用する方法は、DEPRECATED になっている。
https://github.com/codeclimate/ruby-test-reporter

他の依存する gems も古いまま固定されてしまうため、この gem を使わないようにした上で、新しい方法での設定を行なう。

**Comment by ochaochaocha3** [comment]
20d592397914fc3a34f224f1b3e6e1b268c0fc60 で、test reporterのバイナリをダウンロードするようになりました。
