### ISSUE TITLE
キーワード検索での複数チャンネル指定

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#21]
複数チャンネル指定時に、結果表示画面とそのURLがどのような形になればよいか自信がなかったので立ててみました。

# 画面

該当メッセージ一覧で表示する項目に、以下のようにチャンネルを追加する？

> ## 検索結果：こんにちは
>
> ### 2017-03-25
>
> |時刻|チャンネル|メッセージ|
> |----|----|----|
> |12:34:56|#cre|(ocha)<br />こんにちは|
> |11:23:34|#もの書き|(koi-chan)<br />こんにちは|
> ### 2017-03-24
>
> |時刻|チャンネル|メッセージ|
> |----|----|----|
> |12:23:34|#cre|(ocha)<br />こんにちは|
>
> ...

**Comment by koi-chan** [comment]
単純に日時・チャンネルと、検索条件に指定したキーワードをふくむ発言全文を検索結果ページに表示し、リンク先はそのチャンネルの1日分のログの、該当行のアンカーで良いのではないでしょうか。
最初は、現在のポータルのログ(タグ検索)結果のようなモノを想定していたのですが、しかし中身が分からなさすぎ、更に発言の際の文脈も分からなかったので、今は行単位で検索結果を表示する方式が良いと思っています。

grep -r したときのような感じ、でしょうか？

```
$ grep -r -n 'こんにちは'
next/20141103.txt:22:03:20:24 <Marko-mobile> すべてこんにちは。私は英語です。私 は日本語を勉強したい。
cooking/20150117.txt:13:02:26:48 <hisashiburi> こんにちは
cooking/20151027.txt:21:18:07:52 <Nantoka> こんにちは
```

**Comment by ochaochaocha3** [comment]
分かりにくい文章ですみませんでした。結果のページがこんな感じになればいいのかな、という提案でした。
![複数チャンネルを指定したときの検索結果](https://cloud.githubusercontent.com/assets/2551173/24323400/13a46e68-11b8-11e7-9342-32936114db10.png)

**Comment by ochaochaocha3** [comment]
#23で実装できたので終了とします。
