### ISSUE TITLE
「現在の状態」ページに稼働時間が正確に表示されない

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#253]
Puma へ移行したことで、/admin/status の「現在の状態」で表示されるウェブサーバの起動時間が、正確に表示されなくなってしまっていた。

**Comment by koi-chan** [comment]
クラスターモードで起動しているときのみ起こる現象らしい。

**Comment by koi-chan** [comment]
systemd との連携が上手くいかず、実際に再起動していました。
お騒がせしました。

**Comment by ochaochaocha3** [comment]
原因が分かってよかったです！
