### ISSUE TITLE
Rails: ページタイトルを設定ファイルで変更できるようにする

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#26]
ページタイトル(ページ上部と title タグの中身)にある「IRC ログアーカイブ」の文字列を、設定ファイル(もしくはデータベース内に保存する設定)で変えられるようにしたい。

ベータ版として公開するときにはそれを示しておきたいが、現在はソースを直接書き換えなくてはいけない、ですよね？

**Comment by ochaochaocha3** [comment]
はい、現在はソースに直接書いています。Redmineなどと同じように、データベースに設定を保存して管理画面で変えられるようにするのが使いやすいように思います。
