### ISSUE TITLE
チャンネル一覧のページで表示する項目を変更する

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#29]
チャンネル一覧のページで表示する項目を現在の半分デバッグ用の表示から変える。

**Comment by ochaochaocha3** [comment]
[MediaWikiポータル](http://wiki.cre.jp/)のように

1. チャンネル名
2. 最終発言日時

を表示するのはいかがでしょうか？ 

さらに、最終発言日時が最近のものが上に表示されるようにソートすると更新が分かりやすくなると思いました（これもMediaWikiポータルと同じ）。

**Comment by koi-chan** [comment]
チャンネル一覧ページで表示する項目はその2つで良いと思います。

並べ方については、最終発言日時ソートと、表示順を(設定画面で)自由に変えられるようになっているのと、切り替えられるようになっているとより便利かと思います。
あるチャンネルの住人にとっては、常に見るチャンネルが同じ位置にある方が探す手間がなくて便利だと思うからです。

**Comment by ochaochaocha3** [comment]
設定画面で、となると、MediaWikiのようにログインしてお気に入りチャンネルを登録できるようにするところになりそうです。

**Comment by koi-chan** [comment]
将来的にはユーザーが自由に順番を変えられるようになれればいいですが、今は管理者が設定出来ればいいと思います。

**Comment by ochaochaocha3** [comment]
こんな例があるみたいです。WordPressの[Category Orderプラグイン](https://ja.wordpress.org/plugins/taxonomy-terms-order/)みたいなことができそうです。

[Rails 4で作るドラッグアンドドロップで表示順を変更できるサンプルアプリ(スクリーンキャスト付き)](http://qiita.com/jnchito/items/391fb16d3f69fda9bdae)

**Comment by koi-chan** [comment]
意外と簡単に実装出来るのですね。
