### ISSUE TITLE
発言（PRIVMSG・NOTICE）のテーブルを分ける

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#4]
発言（PRIVMSG・NOTICE）は特別に集計する場合があったり全文検索の対象としたりするので、テーブルを分けておくと扱いが楽そう。モデル名としては「Remark」あたりが適当？

他のメッセージと同じように「type」カラムを設けて、Privmsg・Noticeに継承させると扱いやすくなると思われる。

**Comment by koi-chan** [comment]
テーブルを新しく用意するというよりは、view で抽出した方がいいのでは。
処理の重さとデータ量(ディスク占有量)を天秤にかける感じでしょうか。

**Comment by koi-chan** [comment]
簡単に調べた感じだと、rails で DB VIEW を使うのは少し面倒なようですね。
一応解決策っぽいページを見つけたので貼っておきます。
http://blog.mah-lab.com/2014/11/19/rails-db-view/
http://319ring.net/blog/archives/2892/
http://qiita.com/skyriser/items/6503a9f245a26a46dc6d
思いっきり検索上位のページですが。

**Comment by ochaochaocha3** [comment]
ちょうどこれがやれるといいなー、と考えていました。
[Ruby on RailsでMySQLとMroongaを使って日本語全文検索を実現する方法 - ククログ(2015-11-10)](http://www.clear-code.com/blog/2015/11/10.html)

それで全文検索を可能にするためには `message` カラムにインデックスを付けなければならないので、普通検索の対象とするPRIVMSGとNOTICEだけ分離されていると余分なインデックスが付かずに効率的だと考えました。

**Comment by koi-chan** [comment]
#5 に統合します。
