### ISSUE TITLE
一般利用者向けユーザーインターフェースの実装(IRC)

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#48]
一般利用者向けのユーザーインターフェースを実装する。
この issue では、特にIRC側の各機能の管理を行なう。

**Comment by koi-chan** [comment]
PR: #63 にて、ログ公開URLを返すコマンドを実装した。

**Comment by ochaochaocha3** [comment]
現在実装されているコマンドの説明が見られるhelpコマンドを実装したら、一旦完了とします。

**Comment by koi-chan** [comment]
PR #175 にて実装完了しました。
