### ISSUE TITLE
ある特定の一日分のログを検索しづらい

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#49]
ある特定の日のログを検索しようと開始・終了を同じ日付にすると、検索結果が0件になる。
これは、検索条件の終了日の00:00:00までのログを検索しようとしているためだと思われる。
より直感的な操作をできるようにするため、これを終了日の23:59:59までを検索出来るようにしたい。

**Comment by ochaochaocha3** [comment]
ご指摘のとおり、以下の部分のwhereの条件が終了日の00:00:00までになっていますね。これでは確かに指定した日の00:00:00ぴったりの発言しかマッチしません。
https://github.com/cre-ne-jp/log-archiver/blob/64343149581f55d1abf55957583837ff36009aa6/app/models/message_search.rb#L161

以下のように「『終了日』の次の日の00:00:00より前」を指定して試してみます。

```ruby
if @until.present?
  messages = messages.where('timestamp < ?', @until.next_day)
end
```

**Comment by koi-chan** [comment]
そうすると翌日 00:00:00 の発言もマッチしてしまいませんか？

**Comment by koi-chan** [comment]
それとも、SQLの条件式が < であって <= でないからマッチしないんでしょうか。

**Comment by ochaochaocha3** [comment]
等号を除いたので、翌日のものはマッチしないと思います。

**Comment by koi-chan** [comment]
ありがとうございます、お騒がせしました。
