### ISSUE TITLE
メッセージの格納先テーブルを IRC コマンドで分けるか

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#5]
IRC コマンドを定義するテーブルを用意するかどうかの議論をここに残しておきたいです。

**Comment by ochaochaocha3** [comment]
これは一日分のログ一覧表示に強く関係しているので、一旦まとめます。

# したいこと
* ある日付の間に発生したメッセージを 1：時刻の昇順、2：登録順で表示したい（数字はソートの優先度）。
* 発言（PRIVMSGとNOTICE）について全文検索したい。[Mroonga](http://mroonga.org/ja/)を使いたい。

# 問題
* メッセージの種類によって含まれる内容が異なる。
    * どの種類でもタイムスタンプ、チャンネル名、ニックネームは存在する。しかし、JOIN以外の種類だとメッセージと見なせるものが存在するし、KICKは対象者のニックネームも含める必要がある。
    * だからといって、例えばTiarraのログの形式でログの表示そのものを保存して1つのカラムにまとめてはならない。冗長だし、表示を変えようとするときに大変なことになる。

# 解決策
要するにオブジェクト指向の「継承」みたいなことをやりたい、という話。「[エンティティ・アトリビュート・バリュー - Strategic Choice](http://d.hatena.ne.jp/asakichy/20160628/1467065210)」でよくまとまっている。

* シングルテーブル継承
    * ひとつのテーブルにすべての属性を入れてしまう。
    * 現在の実装。
    * 利点
        * テーブルがひとつで済む。
        * Railsで標準サポートされている。
    * 欠点
        * メッセージの種類によっては無駄なカラムが含まれる。
        * 発言の全文検索と相性が悪い。Mroongaでの全文検索にはインデックス付与が必須だが、NULLがあると駄目。構造上どうしてもNULLが入り得るので、おそらく詰んでいる。
* 具象テーブル継承
    * クラスごとにテーブルを分ける。共通の属性もすべてそのテーブルに入れてしまう。
    * 利点
        * 最も単純。
    * 欠点
        * 共通の属性を変えるとき、全テーブルを変えなければならなくなる。
        * 一日分のログ一覧の生成が面倒。おそらく複数回のSELECTが必要。
* クラステーブル継承
    * 共通属性を含むテーブルとサブタイプのテーブルを作る。クラスの継承関係と対応。
    * 利点
        * 共通属性の検索を行いやすい。
    * 欠点
        * 全種類、データが複数のテーブルに保存される。
        * 一日分のログ一覧の生成が面倒。外部結合が何回も必要。

**Comment by ochaochaocha3** [comment]
別の方法として、発言だけテーブルを分けて、それ以外はシングルテーブル継承にすることもできそうです。

**Comment by koi-chan** [comment]
発言(PRIVMSG/NOTICE)だけテーブルを分けるので現段階では必要十分そうに思います。

**Comment by koi-chan** [comment]
書式が同じになるので、PRIVMSG/NOTICE に加え、TOPIC も発言用テーブルにして良いと思うのですが、空文字列の存在も全文検索の障害になるのでしょうか。
他はシングルテーブル継承で良いと思います。

**Comment by ochaochaocha3** [comment]
TOPICを全文検索の対象にするのなら、発言テーブルに入れてもよさそうです。

試していませんが、空文字列は単純に検索で引っかからないだけになるのではないでしょうか。検索の速さを調べてみるのはやったほうがよさそうです。

**Comment by ochaochaocha3** [comment]
現状：

* PRIVMSG・NOTICE・TOPICを発言用テーブル `conversation_messages` にまとめた。
* それ以外は従来の `messages` テーブルのまま。

**Comment by ochaochaocha3** [comment]
これで固まったので、終了とします。
