### ISSUE TITLE
参加・退出のメッセージを既定で表示するべきか

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#51]
似たシステムとして[whitequark/irclogger](https://github.com/whitequark/irclogger)というのがあります。

こちらでは参加・退出のメッセージ（JOINとかQUITとか）が最初は表示されず、チェックボックスで表示するモードに変えられます。最初はログを簡潔に表示して、必要ならばすべてのメッセージを表示することも可能、という方針のようです。

最初の表示が見やすい印象があったのですが、log-archiverにも取り入れた方がよいでしょうか？

**Comment by ochaochaocha3** [comment]
変更点自体は非常に少なく、以下のようにHTMLのチェックボックスのchecked属性を外すだけで実現できます。
https://github.com/cre-ne-jp/log-archiver/compare/89753fcd86786202a3916769570f8af640c9848d...hide-join-part-by-default

**Comment by koi-chan** [comment]
cre のものは、従来通りの形、すなわち表示しているのを初期状態としておく方が良いです。
チェックボックスで非表示に出来ますので、その機能があるだけで十分だと思うからです。

**Comment by ochaochaocha3** [comment]
旭屋さんから

> 20:00:19 \<asahiya\> IN/OUTの履歴はログ参照時ほぼみない、というのはおよそその通りですね。
> 20:00:57 \<asahiya\> たまーに「入退出ログがあった方が観やすいログ」とかもありますが、まあそれはイレギュラーですので( 

というご意見をいただいたのですが、いかがでしょうか？

**Comment by ochaochaocha3** [comment]
どのオプションを標準とするかは難しいのですが、

> 23:14:34 \<Morris\> Nick変更のメッセージも削れないかな
> 23:15:00 \<Morris\> ああ、チェックボックスか
> 23:15:06 \<ocha\> 上のチェックボックスで消せますが、デフォルトで消えていた方が良いでしょうか？
> 23:16:26 \<Morris\> 用途によるでしょうけど
> 23:16:50 \<Morris\> URLの後ろに?つけてチェックボックスのオンオフを指定できるかな

というご意見もいただきました。一番極端なものだと、最初は会話のみに設定する場合もあり得そうです。

上記のようにURLで指定したり、Cookieを使って設定を保存できるようにするとより便利になるのではないかと思います。

**Comment by koi-chan** [comment]
url 指定によってJS(ですよね？)の初期値を上書きできるのは便利だと思います。

Cookie うんぬんといったのは、同じ人は同じ表示項目を好むだろうという推測によるもので、そのため違う日のログでも表示結果が影響されてもいいだろうとの考えによります。

**Comment by ochaochaocha3** [comment]
どちらも便利になると思うので、私も導入には賛成です。

**Comment by koi-chan** [comment]
PR #47 にて結論が出ています。
既定では表示せず、チェックボックスにより切り替えられるようにしてくださいました。
