### ISSUE TITLE
表示するメッセージがないときにその旨を表示する

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#57]
表示するメッセージがないときにその旨を表示する。現状では見出しだけの表が表示されて中途半端な印象がある。

以下はRedmineで表示するチケットがないときの画面。

![Redmineの表示するデータがないときのメッセージ](https://cloud.githubusercontent.com/assets/2551173/25083994/2d03deae-2395-11e7-91e1-4b02270fefd3.png)

**Comment by koi-chan** [comment]
Redmine と同様の処理でいいと思います。
-----
鯉(koi-chan)
koi-chan@mail.kazagakure.net

**Comment by ochaochaocha3** [comment]
ではやってみます！
