### ISSUE TITLE
メッセージの削除(非表示)機能

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#6]
メッセージを何らかの理由(例えばIRCサーバ規約違反など)で非表示にする際、ログデータ自体を削除するのではなく、非表示にする事を設定するカラムを追加したい。
そのカラムに設定する値を、例えば
- 0なら表示(デフォルト)
- 1なら規約違反で削除
- 2なら誰かしらの個人情報のため削除
- 9ならその他の理由で削除

などの理由をつけて非表示にしたい。

**Comment by koi-chan** [comment]
フラグカラムを追加することは悪手らしい。
https://www.slideshare.net/t_wada/ronsakucasual

ので、非表示メッセージ格納用テーブルを作成し、非表示設定をしたメッセージをトランザクション内で通常のテーブルからDELETEし、非表示メッセージテーブルにINSERTすることを考えました。
いかがでしょうか。

**Comment by ochaochaocha3** [comment]
なかなか難しい問題ですね…

基本的には最初の方法（非表示にする事を設定するカラム）で大丈夫そうな気がします。これは上のスライドの最後の方に書いてある「[状態を表すフィールド](https://www.infoq.com/jp/news/2009/09/Do-Not-Delete-Data)」の方法です。

ただ、番号の場合、以下のアンチパターンに注意しておいた方が良さそうです。

[SQLアンチパターン：サーティワンフレーバー (31 のフレーバー)](https://qiita.com/matsuhisa_h/items/c90f2a6b365e69692aac)

上の例ですと削除理由として3番以降が追加されそうに見えるので、これが「流動的な場合はデータを」、つまり削除理由のテーブルを作ってそれと結びつけると、データの整合性を保てると思いました（削除理由のテーブルにない値を指定するとエラーになる）。

**Comment by ochaochaocha3** [comment]
ちょっと面倒そうなのが、「表示」と「その他の理由で削除」をどうやって特別扱いするかでした（WikipediaやスパロボWiki等で使われているMediaWikiの記事の削除で同じ仕組みがあります）。これについてはまた考えたいと思います。

**Comment by ochaochaocha3** [comment]
少し調べたら、MediaWikiの場合「アーカイブ」テーブルがあるようですね。https://github.com/cre-ne-jp/log-archiver/issues/6#issuecomment-344245542 の方法でした。やはりこちらの方がいいのかな。

**Comment by koi-chan** [comment]
ConversationMessage と同じカラムに加え、追加で元の ID と削除(非表示)理由を保存するカラムを持つテーブルを作成し、テーブル間でレコードを移動する形で非表示機能を実装したほうが良いと思います。

```
  create_table "archive_messages", options: "ENGINE=Mroonga" do |t|
    t.integer "old_id", null: false
    t.integer "channel_id"
    t.datetime "timestamp", null: false
    t.string "nick", limit: 64, default: "", null: false
    t.text "message"
    t.string "type"
    t.integer "irc_user_id", default: 1, null: false
    t.integer "archive_reason_id", default: 1, null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "archive_reasons" do |t|
    t.string "reason", null: false
  end
```

**Comment by koi-chan** [comment]
テーブル定義を実装しました。
ArchiveConversationMessage モデルの save! メソッドにて、ConversationMessage テーブルから当該メッセージ削除を自動的に行えるようになっています。

Mroonga ストレージモードにはトランザクション機能がないため、ソフトウェア側でトランザクションに代わる機能を実装した方が良いかもしれません。

ToDo:
* メッセージ非表示理由の編集画面の実装
* メッセージ非表示化処理画面の実装
* 非表示にしたメッセージを再度表示させる機能

**Comment by ochaochaocha3** [comment]
実装をはじめてくださりありがとうございます。

モデル名について、細かいですが「アーカイブされた」の意味で「Archive**d**ConversationMessage」とすると自然だと思いました。

> ArchiveConversationMessage モデルの save! メソッドにて、ConversationMessage テーブルから当該メッセージ削除を自動的に行えるようになっています。

`save!` で複数のモデルにまたがる処理をするのは、1つのモデルクラスの範囲を超えているかもしれません。「会話のメッセージをアーカイブすること」のモデルとして、ConversationMessageArchivingというモデルクラス（ActiveRecordを継承しないふつうのRubyクラス）を app/models/conversation\_message\_archiving.rb として作ることがひとつの方法だと考えています。

**Comment by ochaochaocha3** [comment]
上の処理のようなモデルを[Service Object](https://techracho.bpsinc.jp/hachi8833/2017_10_16/46482)というらしいです。記事で書かれている命名法だと、クラス名は `ConversationMessageArchiver` か `ArchiveConversationMessage` になるようです。

**Comment by koi-chan** [comment]
> モデル名について、細かいですが「アーカイブされた」の意味で「ArchivedConversationMessage」とすると自然だと思いました。

ArchivedConversationMessage テーブルに変更しました。

ConversationMessage から ArchivedConversationMessage にレコードを移動する処理を、追加した ConversationMessageArchiver モデルに移動してみました。
ConversationMessage から新規 ArchivedConversationMessage インスタンスにデータを移動する処理 (attribute_by_conversation_message メソッド)は Archived... 内のままです。
これも移動した方が良いでしょうか(呼び出し方法を迷った結果、そのままにしています)。

**Comment by koi-chan** [comment]
残るは ArchivedConversationMessage から ConversationMessage に戻す(ログを再度表示させるようにする)処理の UI 作成です。

**Comment by ochaochaocha3** [comment]
> ConversationMessage から新規 ArchivedConversationMessage インスタンスにデータを移動する処理 (attribute_by_conversation_message メソッド)は Archived... 内のままです。
> これも移動した方が良いでしょうか(呼び出し方法を迷った結果、そのままにしています)。

ArchivedConversationMessage内での定義で問題ないです。コンストラクタと同等の処理なので、以下のようなクラスメソッドにすると分かりやすいと思います。

```ruby
# ConversationMessage から値をコピーして新しいインスタンスを作る
# @param [ConversationMessage] m 会話メッセージ
# @return [ArchivedConversationMessage] 新しいインスタンス
def self.from_conversation_message(m)
  new(
    old_id: m.id,
    channel_id: m.channel_id,
    timestamp: m.timestamp,
    nick: m.nick,
    message: m.message,
    type: m.type,
    irc_user_id: m.irc_user_id,
    digest: m.digest,
    created_at: m.created_at
  )
end

**Comment by koi-chan** [comment]
例示頂いたメソッドに名前を変更しました。

**Comment by ochaochaocha3** [comment]
現時点の処理では、各チャンネルの最後の発言を非表示に設定できないようです。ConversationMessageをArchivedConversationMessageに移動するときに、ChannelLastSpeechと対応するメッセージが消えてしまい、外部キー制約を満たさなくなってしまうことが原因でした。ConversationMessageを消す前に対応するチャンネルのChannelLastSpeechを削除し、ConversationMessageを消した後にChannelLastSpeechを作り直す必要があります。このあたりの処理は、現在のチャンネル管理ページ内のキャッシュ更新と同様なので、共通化したいと考えています。

**Comment by koi-chan** [comment]
archive_conversation_message-style-temp1 ブランチにて修正して頂いたものを、手動で反映させました。例を作って頂きありがとうございました。

ご指摘頂いた ChannelLastSpeech 周辺を修正しましたが、とりあえず動くモノを作る事を優先したため、共通化はしていない状態です。

**Comment by koi-chan** [comment]
ChannelLastSpeech を更新する共通メソッドを、commit: 307e0f3 にて実装しました。
