### ISSUE TITLE
UserInterface: .log urlの引数未指定時にエラーが出る

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#65]
条件分岐の間違いにより「.log url」だけのときにエラーが出るようです。

* https://github.com/cre-ne-jp/log-archiver/blob/641291fda41796e96bfc452a0be8fc3eeb97c95b/lib/ircs/plugins/user_interface.rb#L17
* https://github.com/cre-ne-jp/log-archiver/blob/641291fda41796e96bfc452a0be8fc3eeb97c95b/lib/ircs/plugins/user_interface.rb#L44-L59

```ruby
# (?: | ) の左側にマッチし、$1はnilになる
match(/url(?:$| (today|yesterday|list))/, method: :url)
```

```ruby
date = case(day)
when 'list'
  send_and_record(m, result)
  return
when 'today'
  Date.today
when 'yesterday'
  Date.today.prev_day
else
  # day == nil なのでここに来る
  begin
    # Date.parse(nil) はTypeErrorを起こす
    Date.parse(day)
  rescue ArgumentError => e
    send_and_record(m, "#{header}日付指定が間違っています")
    return
  end
  # TypeErrorはrescueされないので例外発生
end
```

**Comment by ochaochaocha3** [comment]
リファクタリングのときに一緒に直します。

**Comment by koi-chan** [comment]
list とおなじ処理でいいと思います(そのつもりでいて書き忘れました)。
よろしくお願いします。

**Comment by ochaochaocha3** [comment]
分かりました < list とおなじ処理
メソッドの分け方を少し変え、listの処理を別メソッドで書く予定です。
