### ISSUE TITLE
IRCボット：すべてのプラグインでAtheme Servicesにログインする必要があるか

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/log-archiver#67]
IRCボットのプラグインの基底クラスLogArchiver::Plugin::Baseのコンストラクタに `@ircserv = IrcServ.new` という部分があります。これが実行されるため、すべてのプラグインにおいて読み込み時にAtheme Servicesにログインしようとします。

しかし、LoginNickservを除いてAtheme Servicesを利用しているようには見えません。また、LoginNickservはローカル変数でXMLRPCクライアントを作るので、結局 `@ircserv` は使いません。

したがって、この部分は少なくとも現在の時点では不要ではないでしょうか？

**Comment by koi-chan** [comment]
おっしゃる通り、不要でした。削除して問題ないと思います。

**Comment by ochaochaocha3** [comment]
了解です。

**Comment by koi-chan** [comment]
将来的に、ボットが自身のアカウントでログインしていることを前提に動作するプラグインをかくかもしれません。
その際は、ログイン機能自体をプラグインではなく本体に再実装することになると思います。

**Comment by ochaochaocha3** [comment]
> ボットが自身のアカウントでログインしていることを前提に動作するプラグイン

その場合は、基底クラスのBaseではなくAtheme Servicesを使うプラグインで現在の `@ircserv` のようなインスタンス変数を持つようにすると良いです。
