### ISSUE TITLE
特定の日時のログを一覧する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#79]
現在の実装では、ログの本文はある1日分しか表示することが出来ない。
データベースに保存しているため本来は「1日」という縛りはないはずなので、特定の日時のログを全て表示できるようにしたい。
例：「#もの書き の昨日の22時から今日1時にかけて、日付をまたいで行なわれた会話のログをつなげて(一つの画面で)見たい」

検索を使うと複数チャンネル・範囲指定の日時で抽出が可能だが、出力されるのが(前後のログを含む)本文ではなく、マッチしたその発言しか出てこない。

**Comment by koi-chan** [comment]
雑ですがラフを描いてみました。
https://cloud.githubusercontent.com/assets/8256803/25928938/fa774b30-3639-11e7-9f2a-db45cdd5e96d.jpg

**Comment by ochaochaocha3** [comment]
ありがとうございます！絵があるとやはり分かりやすいです。
タブの名前については、

```
┌─────┬──────┬─────┐
│ 日付 │ 期間 │ 検索 │
┴─────┴──────┴─────┴────
```

のようにすると機能と合うのではないかと思いましたが、いかがでしょうか。

**Comment by koi-chan** [comment]
はい、それでいいと思います。

**Comment by ochaochaocha3** [comment]
少し考えてみたのですが、1ページのメッセージ数を決める（1000メッセージごと等）のが意外と難しいことが分かりました。検索画面では1つのテーブルから読み込んでいるので問題ないのですが、すべての種類のメッセージを表示する場合は2つのテーブルから読み込まなければならないので、単純にページを指定する操作ができません。

2つのテーブルから読み込むために難しくなっていることとして、メッセージのタイムスタンプによるソートもあります。実は現在の1日分のログのページではタイムスタンプによるソートは[ちょっと手を抜いて組んでいます](https://github.com/cre-ne-jp/log-archiver/blob/3bea87e48a0b4d6453c59a39accafa488b38f06b/app/controllers/channels/days_controller.rb#L90-L93)（SQLで行わず、常に通常のメッセージ→会話のメッセージとなるようにRuby側で行っている）。

根本的な解決のためには、通常のメッセージと会話のメッセージの両方を格納するテーブルの追加が必要です。これがなかなか難しく、どのような形にしようか迷っています。最小ならば、順番保持のためのid・種類（messageかconversation_messageか）・参照先のidでいいはずですが、タイムスタンプをどちらに入れれば良いか等が難しいです。

**Comment by koi-chan** [comment]
1ページ数の最大メッセージ数については、実装が難しいようなら省いても良いと思います。
単にDBの負荷が高くなりすぎると困るというだけなので、例えば会話メッセージだけで800件＋その間のその他のメッセージ全て、というような実装でもいいですし。

両方のメッセージを一括して保存するテーブルを作るのであれば、タイムスタンプはそれぞれのメッセージの方に保存するのが良いと思います。
それなら今までの実装を変えなくてもいい(つまり統合テーブルと結合させる必要が無い)からです。

そういえば表示上限ですが、1000件だと1日分の会話メッセージだけで超えることがあるようです。負荷的にもまだ余裕があると思いました。
2000・3000……と実験して上限数を決めたいと思います。
もしくは設定ファイルで決められるようにしておいても良いかもしれません。

**Comment by koi-chan** [comment]
MessageSearch モデルを下敷きに、チャンネル名・日時範囲だけで ConversationMessage の検索を行なうモデルを作成します。
ConversationMessage だけの結果を基にページ分割した後、そのページの最初と最後のメッセージの日時から Message を検索し、両方の結果をソートして表示させるつもりです。

ただ、各ページ最後と次のページ最初の ConversationMessage の間に出力されるはずの Message が表示できなくなるので、その部分をどう工夫するかをまた考えたいと思います。
