### ISSUE TITLE
検索結果一覧ページのチャンネルに設定されたリンクが間違っている

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/log-archiver#94]
ログ検索結果ページのチャンネルに設定されているリンクのURLが間違っている。
誤：hostname/channels.chname
正：hostname/channels/chname

**Comment by ochaochaocha3** [comment]
なかなか対応できずすみません。上記の現象が起こることを確認しました。リンク先の生成のあたりを見直してみます。
